# -*- coding: utf-8 -*-
"""MM220_A2_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JuE_tPJr7Unz5WGKeHqHBGKE2A1tnc0D
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
# %matplotlib inline

#Function used to calculate the function given
def func(a,b,x):
    return a*np.exp(x) + b*np.exp(-x)

#X values to plot the function
x= np.linspace(-6,6,500)

#Plotting begins
plt.subplots(figsize=(8,6))
plt.plot(x, func(2,3,x),'mediumblue')
plt.plot(x, func(4,6,x),'red')
plt.xlabel('x')
plt.ylabel('$Y=ae^{x}+be^{-x}$')
plt.legend(['a=2 , b=3', 'a=4, b=6'])
plt.show()

#Polynomial Fitting of the given function 
#Along with the its plotting
def polyFit(a,b):
    x=np.linspace(-6,6,50)
    y= func(a,b,x) + 0.2*np.random.randn(len(x))
    
    #Fitting the Function
    p1 = np.polyfit(x,y,2)
    p2 = np.polyfit(x,y,3)
    p3 = np.polyfit(x,y,4)
    
    plt.subplots(figsize=(8,6))
    
    plt.plot(x, y,'mediumblue')
    plt.plot(x, np.polyval(p1,x), 'red')
    plt.plot(x, np.polyval(p2,x), 'violet')
    plt.plot(x, np.polyval(p3,x), 'lawngreen')

    plt.xlabel('X')
    plt.ylabel('Y')
    plt.legend(['f(x)','p_2','p_3','p_4'])
    plt.title(f'Coefficients: a={a} , b={b}')
    plt.show()

#Calling the Polynomial Fit Function
polyFit(2,3)
polyFit(4,6)